libs/Bamboo.LoginUi.Web/Pages/Account/Login.cshtml.cs
//using System;
//using System.Security.Claims;
//using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using static System.Runtime.InteropServices.JavaScript.JSType;

using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

using Volo.Abp;
using Volo.Abp.Account.Settings;
using Volo.Abp.Account.Web;
using Volo.Abp.Account.Web.Pages.Account;
using Volo.Abp.AspNetCore.Mvc.UI.RazorPages;
//using Volo.Abp.AspNetCore.Mvc.UI.Theming;
using Volo.Abp.DependencyInjection;
//using Volo.Abp.Domain.Entities;
using Volo.Abp.Guids;
//using Volo.Abp.MultiTenancy;
//using Volo.Abp.OpenIddict;
//using Volo.Abp.Security.Claims;

using Volo.Abp.Auditing;
using Volo.Abp.Identity;
using Volo.Abp.Identity.AspNetCore;
using Volo.Abp.Security.Claims;
using Volo.Abp.Settings;
using Volo.Abp.Validation;

using IdentityUser = Volo.Abp.Identity.IdentityUser;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

using static Volo.Abp.Identity.IdentityPermissions;
using static Volo.Abp.UI.Navigation.DefaultMenuNames.Application;

//using IdentityModel;
using Telegram.Bot.Extensions.LoginWidget;

namespace Bamboo.Abp.LoginUi.Web.Pages.Account;

public class LoginUiLoginModel : LoginModel
{
    public bool EnableTelegram { get; set; }
    public string TelegramWidget { get; set; }

    public LoginUiLoginModel(
        IConfiguration config,
        IAuthenticationSchemeProvider schemeProvider,
        IOptions<AbpAccountOptions> accountOptions,
        IOptions<IdentityOptions> identityOptions,
        IdentityDynamicClaimsPrincipalContributorCache cache)
        : base(schemeProvider, accountOptions, identityOptions, cache)
    {
        var section = config.GetSection("Telegram");
        WidgetEmbedCodeGenerator.LoginWidgetJsVersion = 22;
        if (section.Exists() && section.GetValue<bool>("IsEnabled", false))
        {
            EnableTelegram = true;
            var botName = section["BotName"];
            var LoginCallback = section["LoginCallback"];
            var useLargeButton = section.GetValue<bool>("Large", false);
            TelegramWidget = WidgetEmbedCodeGenerator.GenerateRedirectEmbedCode(
            botName,
            LoginCallback,            
            useLargeButton?ButtonStyle.Large: ButtonStyle.Medium,
            true,
            true);
        }        
    }

    public override async Task<IActionResult> OnPostExternalLogin(string provider)
    {
        var redirectUrl = Url.Page("./Login", pageHandler: "ExternalLoginCallback", values: new { ReturnUrl, ReturnUrlHash });
        var properties = SignInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
        properties.Items["scheme"] = provider;

        return await Task.FromResult(Challenge(properties, provider));
    }

    public override async Task<IActionResult> OnGetExternalLoginCallbackAsync(string returnUrl = "", string returnUrlHash = "", string remoteError = null)
    {
        //return await base.OnGetExternalLoginCallbackAsync(returnUrl, returnUrlHash, remoteError);

        //TODO: Did not implemented Identity Server 4 sample for this method (see ExternalLoginCallback in Quickstart of IDS4 sample)
        /* Also did not implement these:
         * - Logout(string logoutId)
         */

        if (remoteError != null)
        {
            Logger.LogWarning($"External login callback error: {remoteError}");
            return RedirectToPage("./Login");
        }

        await IdentityOptions.SetAsync();

        var loginInfo = await SignInManager.GetExternalLoginInfoAsync();
        if (loginInfo == null)
        {
            Logger.LogWarning("External login info is not available");
            return RedirectToPage("./Login");
        }

        var result = await SignInManager.ExternalLoginSignInAsync(
            loginInfo.LoginProvider,
            loginInfo.ProviderKey,
            isPersistent: false,
            bypassTwoFactor: true
        );

        if (!result.Succeeded)
        {
            await IdentitySecurityLogManager.SaveAsync(new IdentitySecurityLogContext()
            {
                Identity = IdentitySecurityLogIdentityConsts.IdentityExternal,
                Action = "Login" + result
            });
        }

        if (result.IsLockedOut)
        {
            Logger.LogWarning($"External login callback error: user is locked out!");
            throw new UserFriendlyException("Cannot proceed because user is locked out!");
        }

        if (result.IsNotAllowed)
        {
            Logger.LogWarning($"External login callback error: user is not allowed!");
            throw new UserFriendlyException("Cannot proceed because user is not allowed!");
        }

        IdentityUser user;
        if (result.Succeeded)
        {
            user = await UserManager.FindByLoginAsync(loginInfo.LoginProvider, loginInfo.ProviderKey);
            if (user != null)
            {
                // Clear the dynamic claims cache.
                await IdentityDynamicClaimsPrincipalContributorCache.ClearAsync(user.Id, user.TenantId);
            }

            return await RedirectSafelyAsync(returnUrl, returnUrlHash);
        }

        //TODO: Handle other cases for result!

        var email = loginInfo.Principal.FindFirstValue(AbpClaimTypes.Email) ?? loginInfo.Principal.FindFirstValue(ClaimTypes.Email);
        if (email.IsNullOrWhiteSpace())
        {
            return RedirectToPage("./Register", new
            {
                IsExternalLogin = true,
                ExternalLoginAuthSchema = loginInfo.LoginProvider,
                ReturnUrl = returnUrl
            });
        }

        user = await UserManager.FindByEmailAsync(email);
        if (user == null)
        {
            return RedirectToPage("./Register", new
            {
                IsExternalLogin = true,
                ExternalLoginAuthSchema = loginInfo.LoginProvider,
                ReturnUrl = returnUrl
            });
        }

        if (await UserManager.FindByLoginAsync(loginInfo.LoginProvider, loginInfo.ProviderKey) == null)
        {
            CheckIdentityErrors(await UserManager.AddLoginAsync(user, loginInfo));
        }

        await SignInManager.SignInAsync(user, false);

        await IdentitySecurityLogManager.SaveAsync(new IdentitySecurityLogContext()
        {
            Identity = IdentitySecurityLogIdentityConsts.IdentityExternal,
            Action = result.ToIdentitySecurityLogAction(),
            UserName = user.Name
        });

        // Clear the dynamic claims cache.
        await IdentityDynamicClaimsPrincipalContributorCache.ClearAsync(user.Id, user.TenantId);

        return await RedirectSafelyAsync(returnUrl, returnUrlHash);
    }
        //protected override async Task<IdentityUser> CreateExternalUserAsync(ExternalLoginInfo info)
        //{
        //    //ClaimsPrincipal principal;
        //    var emailAddress = info.Principal.FindFirstValue(AbpClaimTypes.Email);
        //    var userId = GuidGenerator.Create();
        //    var user = new IdentityUser(userId, emailAddress, emailAddress, CurrentTenant.Id)
        //    {
        //        // This claim will be null if using AzureAD v2.0 endpoint
        //        Name = info.Principal.FindFirstValue(JwtClaimTypes.GivenName),
        //        // This claim will be null if using AzureAD v2.0 endpoint
        //        Surname = info.Principal.FindFirstValue(JwtClaimTypes.FamilyName),
        //        IsExternal = true
        //    };

        //    //Optional: Add claims to user claims
        //    if (!string.IsNullOrEmpty(info.Principal.FindFirstValue(JwtClaimTypes.GivenName)))
        //    {
        //        user.Claims.Add(new Volo.Abp.Identity.IdentityUserClaim(GuidGenerator.Create(), userId,
        //            JwtClaimTypes.GivenName, info.Principal.FindFirstValue(JwtClaimTypes.GivenName), CurrentTenant.Id));
        //    }

        //    if (!string.IsNullOrEmpty(info.Principal.FindFirstValue(JwtClaimTypes.FamilyName)))
        //    {
        //        user.Claims.Add(new Volo.Abp.Identity.IdentityUserClaim(GuidGenerator.Create(), userId,
        //            JwtClaimTypes.FamilyName, info.Principal.FindFirstValue(JwtClaimTypes.FamilyName),
        //            CurrentTenant.Id));
        //    }

        //    CheckIdentityErrors(await UserManager.CreateAsync(user));
        //    CheckIdentityErrors(await UserManager.SetEmailAsync(user, emailAddress));
        //    CheckIdentityErrors(await UserManager.AddLoginAsync(user, info));

        //    return user;
        //}
    }

//[ExposeServices(typeof(LoginModel))]
//public class LoginUiLoginModel : OpenIddictSupportedLoginModel
//{
//    private readonly ITenantRepository _tenantRepository;

//    public LoginUiLoginModel(
//        IAuthenticationSchemeProvider schemeProvider,
//        IOptions<AbpAccountOptions> accountOptions,
//        IOptions<IdentityOptions> identityOptions,
//        AbpOpenIddictRequestHelper openIddictRequestHelper)
//        : base(schemeProvider, accountOptions, identityOptions, openIddictRequestHelper)
//    {
//        _tenantRepository = tenantRepository;
//    }

//    public override async Task<IActionResult> OnPostAsync(string action)
//    {
//        return await base.OnPostAsync(action);
//        var user = await FindUserAsync(LoginInput.UserNameOrEmailAddress);
//        using (CurrentTenant.Change(user?.TenantId))
//        {
//            return await base.OnPostAsync(action);
//        }
//    }

libs/Bamboo.LoginUi.Web/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Volo.Abp;
using Volo.Abp.Account;
using Volo.Abp.Account.Settings;
using Volo.Abp.Account.Web;
using Volo.Abp.Account.Web.Pages.Account;
using Volo.Abp.Auditing;
using Volo.Abp.Identity;
using Volo.Abp.Security.Claims;
using Volo.Abp.Settings;
using Volo.Abp.Validation;
using IdentityUser = Volo.Abp.Identity.IdentityUser;
namespace Bamboo.Abp.LoginUi.Web.Pages.Account;

public class LoginUiRegisterModel : RegisterModel
{
    public LoginUiRegisterModel(
        IAccountAppService accountAppService,
        IAuthenticationSchemeProvider schemeProvider,
        IOptions<AbpAccountOptions> accountOptions,
        IdentityDynamicClaimsPrincipalContributorCache identityDynamicClaimsPrincipalContributorCache)
        : base(accountAppService, schemeProvider, accountOptions, identityDynamicClaimsPrincipalContributorCache)
    {
    }

    public override async Task<IActionResult> OnGetAsync()
    {
        ExternalProviders = await GetExternalProviders();

        if (!await CheckSelfRegistrationAsync())
        {
            if (IsExternalLoginOnly)
            {
                return await OnPostExternalLogin(ExternalLoginScheme);
            }

            Alerts.Warning(L["SelfRegistrationDisabledMessage"]);
        }

        await TrySetEmailAsync();

        return Page();
    }

    protected override async Task TrySetEmailAsync()
    {
        if (IsExternalLogin)
        {
            var externalLoginInfo = await SignInManager.GetExternalLoginInfoAsync();
            if (externalLoginInfo == null)
            {
                return;
            }

            if (!externalLoginInfo.Principal.Identities.Any())
            {
                return;
            }

            var identity = externalLoginInfo.Principal.Identities.First();
            var emailClaim = identity.FindFirst(AbpClaimTypes.Email) ?? identity.FindFirst(ClaimTypes.Email);

            if (emailClaim == null)
            {
                return;
            }

            var userName = await UserManager.GetUserNameFromEmailAsync(emailClaim.Value);
            Input = new PostInput { UserName = userName, EmailAddress = emailClaim.Value };
        }
    }

    public override async Task<IActionResult> OnPostAsync()
    {
        try
        {
            ExternalProviders = await GetExternalProviders();

            if (!await CheckSelfRegistrationAsync())
            {
                throw new UserFriendlyException(L["SelfRegistrationDisabledMessage"]);
            }

            if (IsExternalLogin)
            {
                var externalLoginInfo = await SignInManager.GetExternalLoginInfoAsync();
                if (externalLoginInfo == null)
                {
                    Logger.LogWarning("External login info is not available");
                    return RedirectToPage("./Login");
                }
                if (Input.UserName.IsNullOrWhiteSpace())
                {
                    Input.UserName = await UserManager.GetUserNameFromEmailAsync(Input.EmailAddress);
                }
                await RegisterExternalUserAsync(externalLoginInfo, Input.UserName, Input.EmailAddress);
            }
            else
            {
                await RegisterLocalUserAsync();
            }

            return Redirect(ReturnUrl ?? "~/"); //TODO: How to ensure safety? IdentityServer requires it however it should be checked somehow!
        }
        catch (BusinessException e)
        {
            Alerts.Danger(GetLocalizeExceptionMessage(e));
            return Page();
        }
    }
    protected override async Task RegisterExternalUserAsync(ExternalLoginInfo externalLoginInfo, string userName, string emailAddress)
    {
        await IdentityOptions.SetAsync();

        var user = new IdentityUser(GuidGenerator.Create(), userName, emailAddress, CurrentTenant.Id);

        (await UserManager.CreateAsync(user)).CheckErrors();
        (await UserManager.AddDefaultRolesAsync(user)).CheckErrors();

        var userLoginAlreadyExists = user.Logins.Any(x =>
            x.TenantId == user.TenantId &&
            x.LoginProvider == externalLoginInfo.LoginProvider &&
            x.ProviderKey == externalLoginInfo.ProviderKey);

        if (!userLoginAlreadyExists)
        {
            (await UserManager.AddLoginAsync(user, new UserLoginInfo(
                externalLoginInfo.LoginProvider,
                externalLoginInfo.ProviderKey,
                externalLoginInfo.ProviderDisplayName
            ))).CheckErrors();
        }

        await SignInManager.SignInAsync(user, isPersistent: true, ExternalLoginAuthSchema);

        // Clear the dynamic claims cache.
        await IdentityDynamicClaimsPrincipalContributorCache.ClearAsync(user.Id, user.TenantId);
    }
}

libs/Bamboo.LoginUi.Web/Pages/Components/ExternalLoginWidget/ExternalLoginWidgetViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Volo.Abp.AspNetCore.Mvc;

namespace Bamboo.Abp.LoginUi.Web.Pages.Components.ExternalLoginWidget;

public class ExternalLoginWidgetViewComponent : AbpViewComponent
{
    public IViewComponentResult Invoke(ExternalLoginWidgetModel model)
    {
        return View("Default", model);
    }
}

libs/Bamboo.LoginUi.Web/Pages/Account/Login.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.Account.Settings
@using Volo.Abp.Settings

@using Volo.Abp.Account.Localization
@using Volo.Abp.Account.Web.Pages.Account;
@using Volo.Abp.AspNetCore.Mvc.UI.Theming;
@using Volo.Abp.Identity;
@using Telegram.Bot.Extensions.LoginWidget
@using Bamboo.Abp.LoginUi.Web.Localization
@using Bamboo.Abp.LoginUi.Web.Pages.Components.ExternalLoginWidget

@inject IHtmlLocalizer<AbpLoginUiResource> L
@inject ISettingProvider SettingProvider
@inject IThemeManager ThemeManager
@inject Volo.Abp.Settings.ISettingProvider SettingProvider

@model Bamboo.Abp.LoginUi.Web.Pages.Account.LoginUiLoginModel

@{
    Layout = ThemeManager.CurrentTheme.GetAccountLayout();
}

@*<abp-style-bundle>
        <abp-style src="/Pages/Account/Login.cshtml.css" />
    </abp-style-bundle>*@

<div class="card mt-3 shadow-sm rounded">
    <div class="card-body p-5">
        <h4>@L["Login"]</h4>
        @*@if (await SettingProvider.IsTrueAsync(AccountSettingNames.IsSelfRegistrationEnabled))
            {
                <strong>
                    @L["AreYouANewUser"]
                    <a href="@Url.Page("./Register", new {returnUrl = Model.ReturnUrl, returnUrlHash = Model.ReturnUrlHash})" class="text-decoration-none">@L["Register"]</a>
                </strong>
        }*@
        @if (Model.EnableLocalLogin)
        {
            <form method="post" class="mt-4">
                <div class="mb-3">
                    <label asp-for="LoginInput.UserNameOrEmailAddress" class="form-label">Phone / Email</label>
                    <input asp-for="LoginInput.UserNameOrEmailAddress" class="form-control" />
                    <span asp-validation-for="LoginInput.UserNameOrEmailAddress" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="LoginInput.Password" class="form-label"></label>
                    <input asp-for="LoginInput.Password" class="form-control" />
                    <span asp-validation-for="LoginInput.Password" class="text-danger"></span>
                </div>
                <abp-row>
                    <abp-column>
                        <abp-input asp-for="LoginInput.RememberMe" class="mb-4" />
                    </abp-column>
                    <abp-column class="text-end">
                        <a href="@Url.Page("./ForgotPassword", new { returnUrl = Model.ReturnUrl, returnUrlHash = Model.ReturnUrlHash })">@L["ForgotPassword"]</a>
                    </abp-column>
                </abp-row>
                <div class="d-grid gap-2">
                    <abp-button type="submit" button-type="Primary" name="Action" value="Login" class="btn-lg mt-3">@L["Login"]</abp-button>
                    @if (Model.ShowCancelButton)
                    {
                        <abp-button type="submit" button-type="Secondary" formnovalidate="formnovalidate" name="Action" value="Cancel" class="btn-lg mt-3">@L["Cancel"]</abp-button>
                    }
                </div>
            </form>
        }

        @if (Model.VisibleExternalProviders.Any() || Model.EnableTelegram)
        {
            <div class="d-flex block-center mt-4" style="align-items: center;">
                <div class="divider"></div>
                @*<span class="divider-text text-caption mx-4">@L["OrLoginWith"]</span>*@
                <div class="divider"></div>
            </div>
            <div class="container">
                @if (Model.EnableTelegram)
                {
                    <div class="mt-3">
                        @Html.Raw(Model.TelegramWidget)
                    </div>
                }
                @if (Model.VisibleExternalProviders.Any())
                {
                    <div class="mt-3">
                        @await Component.InvokeAsync("ExternalLoginWidget", new ExternalLoginWidgetModel(Model.VisibleExternalProviders, Model.ReturnUrl, Model.ReturnUrlHash))
                    </div>
                }
            </div>
        }
        @{
            @*
            https://stackoverflow.com/questions/68157777/implementing-telegram-loginwidget-with-signinmanager
            string widget = WidgetEmbedCodeGenerator.GenerateRedirectEmbedCode(
            _config["BOT_NAME"],
            $"https://{_config["AuthServer:Authority"]}/{Url.Action("tgcallback", "account")}",
            ButtonStyle.Large,
            true,
            true);
            *@            
        }

        @if (!Model.EnableLocalLogin && !Model.VisibleExternalProviders.Any())
        {
            <div class="alert alert-warning">
                <strong>@L["InvalidLoginRequest"]</strong>
                @L["ThereAreNoLoginSchemesConfiguredForThisClient"]
            </div>
        }

    </div>
</div>

libs/Bamboo.LoginUi.Web/Pages/Account/Register.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.Account.Localization
@model Bamboo.Abp.LoginUi.Web.Pages.Account.LoginUiRegisterModel

@inject IHtmlLocalizer<AccountResource> L

<div class="card mt-3 shadow-sm rounded">
    <div class="card-body p-5">
        <h4>@L["Register"]</h4>
        <strong>
            @L["AlreadyRegistered"]
            <a href="@Url.Page("./Login", new {returnUrl = Model.ReturnUrl, returnUrlHash = Model.ReturnUrlHash})" class="text-decoration-none">@L["Login"]</a>
        </strong>
        <form method="post" class="mt-4">
            @if (Model.IsExternalLogin && Model.VisibleExternalProviders.Any())
            {                 
                <abp-input asp-for="Input.UserName" auto-focus="true" />
                <abp-input asp-for="Input.EmailAddress" />
                <abp-input asp-for="Input.Password" />
                <div class="d-grid gap-2">
                    <abp-button button-type="Primary" type="submit" class="btn-lg mt-4">@L["Register"]</abp-button>
                </div>
            }
        </form>

        @if (!Model.IsExternalLogin && Model.VisibleExternalProviders.Any())
        {
            <div class="mt-2">
                <h5>@L["OrRegisterWith"]</h5>
                <form asp-page="./Login" asp-page-handler="ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl" asp-route-returnUrlHash="@Model.ReturnUrlHash" method="post">
                    @foreach (var provider in Model.VisibleExternalProviders)
                    {
                        <button type="submit" class="btn btn-primary m-1" name="provider" value="@provider.AuthenticationScheme" title="@L["RegisterUsingYourProviderAccount", provider.DisplayName]">@provider.DisplayName</button>
                    }
                </form>
            </div>
        }

    </div>
</div>